executable              = /var/clus/usera/jjd49/lardirection_pandora/CondorUtilities/scripts/pandora.sh                
initial_dir             = /var/clus/usera/jjd49/lardirection_pandora/CondorUtilities                  
notification            = never                                                 
requirements            = (OSTYPE == "SLC6") && (LoadAvg < 0.5)               
request_memory          = 1024                                                  
rank                    = memory                                                
output                  = /var/clus/usera/jjd49/lardirection_pandora/CondorUtilities/log/larreco.out 
error                   = /var/clus/usera/jjd49/lardirection_pandora/CondorUtilities/log/larreco.err 
log                     = /var/clus/usera/jjd49/lardirection_pandora/CondorUtilities/log/larreco.log 
environment             = CONDOR_JOB=true                                       
universe                = vanilla                                               
getenv                  = false                                                 
copy_to_spool           = true                                                  
should_transfer_files   = yes                                                   
when_to_transfer_output = on_exit_or_evict                                      
arguments = ~jjd49/lardirection_pandora/LArReco/bin/PandoraInterface 100 ~jjd49/lardirection_pandora/setup.sh Full /usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_91.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_92.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_93.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_94.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_95.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_96.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_97.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_98.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_99.xml@/usera/jjd49/lardirection_pandora/CondorUtilities/xmls/PandoraSettings_100.xml

queue 1 
